# Generated by Django 5.0.3 on 2024-03-04 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='guid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='linea',
            old_name='guid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='proceso',
            old_name='guid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='tipo',
            old_name='guid',
            new_name='id',
        ),
    ]
